name: SkycadeChunkCollectors
version: 1.0.1-SNAPSHOT
main: net.skycade.skycadechunkcollectors.SkycadeChunkCollectorsPlugin
description: Chunk Collectors
api-version: 1.16
authors: ["Christian Doughty (Taon2)"]
depend: [SkycadeCore]
softdepend: [Factions, SkycadeSkyblock, SkycadeClaims]